### PR TITLE
Add a Setup.py

### PR DESCRIPTION
**Pull request by thast**
With this PR, it is now possible to do:
- `pip install git+https://github.com/simpeg/tle-magnetotelluric_inversion`
- `import tleMT`

### CODE REVIEW

**Comment by lheagy** [comment]
Thanks @thast! Are the links in the index notebook up to date?

**Comment by thast** [comment]
@lheagy : I had to go a bit further than expected to get it up and running in a travis environment. I'm dealing with those type of things (links etc.) right now. Will keep you posted once done.

**Comment by thast** [comment]
@lheagy : ready again ^^, thanks for your patience.

**Review by lheagy — APPROVED** [review]
many thanks for this @thast!

**Pull request merged**
